# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Abraham Veloz
title: Estudiante Ingenieria en Computación
email: abrahamveloz721@gmail.com
website: https://github.com/AbrahamVeloz/modern-resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: veloz_abraham
github_username:  AbrahamVeloz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: Veloz_Abraham
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
   Hola mi nombre es Abraham Veloz soy un programador novato y espero algun dia tener la experiencia suficiente para tener un buen trabajo o trabajar por mi propia cuenta.



content:
  - title: Proyecto # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/AbrahamVeloz
        # link_text: Project Website
        additional_links:
          - title:  AbrahamVeloz/modern-resume-theme
            icon: fab fa-github
            url: github.com/AbrahamVeloz/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Esto solo es para mi cv
        description: | # this will include new lines to allow paragraphs
          Este CV me servira para que en futura quien quiera saber un poco mas de mi pueda ver mi informacion y a lo que me dedico o en lo que estoy trabajando.

  - title: Experiencia # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Por el momento no he trabajado 
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Espero algun dia tener una gran oportunidad
        caption: F
        quote: >
          En busca de un trabajo
        description: | # this will include new lines to allow paragraphs
            En busca de un trabajo

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cucei
        caption: 2021 - Presente
        sub_title: Ingenieria en Computacion
        quote: >
          Sigo estudiando mi carrera en el CUCEI.
        description: | # this will include new lines to allow paragraphs
          Por el momento no tengo experiencias en el ambiente laboral, solo tengo los proyectos que he hecho con amigos por iniciativa propia o proyectos escolares ya sea en solitario o en equipo de varias personas.

          CUCEI

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
