# Site
repository: AbrahamVeloz/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Veloz Alcaraz Axel Abraham
title: Estudiante de Ingeniera en Computacion
email: abrahamveloz721@gmail.com
website: www.github.com/AbrahamVeloz/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: facespics
github_username: AbrahamVeloz
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: Veloz_abraham
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: Abraham Veloz
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hola mi nombre es Abraham Veloz soy un programador novato y espero algun dia tener la experiencia suficiente para tener un buen trabajo o trabajar por mi propia cuenta.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/AbrahamVeloz
        # link_text: Project Website
        additional_links:
          - title: AbrahamVeloz/modern-resume-theme
            icon: fab fa-github
            url: github.com/AbrahamVeloz/modern-resume-theme
        quote: >
          Este seria mi proyecto de cv
        description: |
          Este CV me servira para que en futura quien quiera saber un poco mas de mi pueda ver mi informacion y a lo que me dedico o en lo que estoy trabajando:

  - title: Experiencia
    layout: list
    content:
      - layout: left
        title: Escuela
        link:
        # link_text: boringcompany.com
        sub_title: Estudiante
        caption: 2020 - Present
        quote: >
          Sigo estudiando mi carrera en el CUCEI
        description: |
          Por el momento no tengo experiencias en el ambiente laboral, solo tengo los proyectos que he hecho con amigos por iniciativa propia o proyectos escolares ya sea en solitario o en equipo de varias personas.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2020 - 2024
        sub_title: Centro Universitario de Ciencias Exactas e ingenieras
        quote: >
          Established in es la división de la Universidad de Guadalajara en Jalisco, México, destinada a la educación superior relacionada con los campos de ingenierías, ciencias físicas, químicas y matemáticas.
          
          Durante mi estancia en mi carrera en CUCEI, he aprendido los principales fundamentos y técnicas de la programación. Además de estos conocimientos, he adquirido experiencia en las metodologías de trabajo que se utilizan en las grandes empresas.

  - title: Mas cosas sobre mi
    layout: text
    content: |
      Algunas otras cosas interesantes sobre mi seria que:
      - Me gusta cocinar
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: AbrahamVeloz/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
